TicketsUNO27/Models/Tickets/Tickets.cs
using AppRecordatorio.Models.Areas;
using AppRecordatorio.Models.Estados;
using AppRecordatorio.Models.TipoCasos;
using Core.Models.Common;
using Core.Models.User;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppRecordatorio.Models.TicketsCasos
{
    public class Tickets : EntityWithIntId
    {
        public int IdUsuario { get; set; } 
        public int IdArea { get; set; }
        public int IdTipoCaso { get; set; }

        [Display(Name = "Fecha Finalizacion")]
        public DateTime? FechaFinalizacion { get; set; }
        public int IdEstado { get; set; }
        public int? IdTipoAtencion { get; set; }
        public string Incidente { get; set; }
        public string Respuesta { get; set; }
        public string DetalleDemoraGestion { get; set; }

        [Display(Name = "Asignado")]
        public int? IdAsignado { get; set; }       

        [Display(Name = "Asignado Por")]
        public int? IdAsignadoPor { get; set; }
        public string Modalidad { get; set; }
        public string IpUsuario { get; set; }

        [Display(Name = "Notas Ticket")]
        public string Notas { get; set; }

        public int? CreadoPor { get; set; }
        public int? ActualizadoPor { get; set; }

        #region

        [ForeignKey("IdUsuario")]
        public User User { get; set; }

        [ForeignKey("IdAsignadoPor")]
        public User AsignadoPor { get; set; }

        [ForeignKey("IdAsignado")]
        public User Users { get; set; }

        [ForeignKey("IdArea")]
        public Area Area { get; set; }

        [ForeignKey("IdEstado")]
        public Estado Estados { get; set; }

        [ForeignKey("IdTipoAtencion")]
        public Estado TipoAtencion { get; set; }

        [ForeignKey("IdTipoCaso")]
        public TipoCaso TipoCaso { get; set; }
        #endregion
    }
}

TicketsUNO27/Controllers/DetalleEstadoTicketController.cs
using AppRecordatorio.Models;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace TicketsUNO27.Controllers
{
    public class DetalleEstadoTicketController : Controller
    {
        private Contexto db = new Contexto();
        // GET: DetalleEstadoTicket
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ResumentTicket(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var tickets = db.Tickets.Where(ts => ts.Id == id).Include(t => t.TipoCaso).Include(e => e.Estados).Include(a => a.Area).Include(u => u.User).Include(u => u.User.Campana).Include(u => u.Users).FirstOrDefault();

            if (tickets == null)
            {
                return HttpNotFound();
            }
            ViewBag.Modalidad = tickets.Modalidad;
            ViewBag.IdAsignadoPor = tickets.IdAsignadoPor;
            ViewBag.IdTipoCaso = new SelectList(db.TipoCasos, "Id", "Nombre", tickets.IdTipoCaso);
            ViewBag.IdUsuario = new SelectList(db.Usuario, "Id", "Documento", tickets.IdUsuario);
            ViewBag.IdEstado = new SelectList(db.Estados.Where(e => e.Id == 8), "Id", "Nombre", tickets.IdEstado);
            ViewBag.HistorialTicket = db.HistorialTickets.Where(t => t.IdTicket == id).Include(e => e.Estados).Include(u => u.TicketAsignadoA).Include(u => u.TicketAsignadoPor).ToList();
            return View(tickets);
        }
    }
}

TicketsUNO27/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppRecordatorio.Models;
using AppRecordatorio.Models.TicketsCasos;
using Core.Models.Security;
using PagedList;
using TicketsUNO27.Models.Archivos;
using TicketsUNO27.Models.Constants;
using TicketsUNO27.Models.Historial;
using TicketsUNO27.ViewModel;

namespace TicketsUNO27.Controllers
{
    public class TicketsController : Controller
    {
        private Contexto db = new Contexto();

        // GET: Tickets
        public ActionResult Index()
        {


            var usuario = SessionPersister.Id;

            var rol = db.UsuariosRoles.Where(ur => ur.UserId == usuario).Select(r => r.Rol.Name).FirstOrDefault();

            if (rol == "Soporte Asignacion")
            {
                ViewBag.Usuarios = new SelectList(db.UsuariosRoles.Where(ur => ur.UserId == usuario).Include(u => u.User).Select(c => new { c.UserId, Name = c.User.Nombres + "(" + c.User.Apellidos + ")" }), "UserId", "Name");

            }
            if (rol == "Lider Soporte" || rol == "Administrador")
            {
                ViewBag.Usuarios = new SelectList(db.UsuariosRoles.Where(ur => ur.RolId == 2 || ur.RolId == 3 || ur.RolId == 6).Include(u => u.User).Select(c => new { c.UserId, Name = c.User.Nombres + "(" + c.User.Apellidos + ")" }), "UserId", "Name");
            }

            ViewBag.SinAsignar = db.Tickets.Where(d => d.Estados.Nombre == "Nuevo").Count();
            ViewBag.EnProgreso = db.Tickets.Where(d => d.IdEstado == 3).Count();
            ViewBag.Resueltos = db.Tickets.Where(d => d.IdEstado == 4).Count();
            ViewBag.PrioridadAlta = Constants.PrioridadAlta;
            ViewBag.PrioridadMedia = Constants.PrioridadMedia;
            ViewBag.PrioridadBaja = Constants.PrioridadBaja;

            return View();
        }

        public ActionResult VerTicketsSoporte()
        {
            return View();
        }

        public ActionResult CargarTickets()
        {

            var usuario = SessionPersister.Id;
            List<Tickets> data = null;

            var rol = db.UsuariosRoles.Where(ur => ur.UserId == usuario).Select(r => r.Rol).FirstOrDefault();

            if (rol.Name == "Lider Soporte")
            {
                data = db.Tickets.Where(t => (t.IdAsignado == 853 || t.IdAsignado == usuario || t.IdEstado == 2 || t.IdEstado == 3) && t.IdEstado != 4 && t.IdEstado != 5 && t.IdEstado != 6 && t.IdArea != 2).Include(t => t.TipoCaso).Include(e => e.Estados).Include(a => a.Area).Include(u => u.User).Include(c => c.User.Campana).Include(u => u.Users).ToList();
            }
            if (rol.Name == "Soporte Asignacion")
            {
                data = db.Tickets.Where(t => (t.IdAsignado == 853 || t.IdAsignado == usuario || t.IdEstado == 2 || t.IdEstado == 3) && t.IdEstado != 4 && t.IdEstado != 5 && t.IdEstado != 6 && t.IdArea != 2).Include(t => t.TipoCaso).Include(e => e.Estados).Include(a => a.Area).Include(u => u.User).Include(c => c.User.Campana).Include(u => u.Users).ToList();
            }
            if (rol.Name == "Soporte")
            {
                data = db.Tickets.Where(ts => ts.Area.Nombre == rol.Name && ts.IdAsignado == usuario && ts.IdEstado != 4 && ts.IdEstado != 5 && ts.IdEstado != 6 && ts.IdArea != 2).Include(t => t.TipoCaso).Include(e => e.Estados).Include(a => a.Area).Include(u => u.User).Include(c => c.User.Campana).Include(u => u.Users).ToList();
            }

            if (rol.Name == "Recursos Humanos")
            {
                data = db.Tickets.Where(ts => ts.Area.Nombre == rol.Name && ts.IdAsignado == usuario && ts.IdEstado != 4 && ts.IdEstado != 5 && ts.IdEstado != 6).Include(t => t.TipoCaso).Include(e => e.Estados).Include(a => a.Area).Include(u => u.User).Include(c => c.User.Campana).Include(u => u.Users).ToList();
            }


            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ListaEstadoTickets(int? page, string ticket, string estado)
        {
            int pageSize = Convert.ToInt32(ConfigurationManager.AppSettings["pagination"]);

            int pageNumber = (page ?? 1);


            var data = db.Tickets
                 .Where(t => t.Id.ToString().StartsWith(ticket.Trim()) || ticket == null || ticket == "")
                 .Where(t => t.IdEstado.ToString().StartsWith(estado.Trim()) || estado == null || estado == "")
                .Include(d => d.Estados)
                .Include(t => t.TipoCaso)
                .Include(e => e.Estados)
                .Include(a => a.Area)
                .Include(u => u.User)
                .Include(c => c.User.Campana).Include(a => a.Users)
                .OrderByDescending(c => c.CreatedAt)
                .ToPagedList(pageNumber, pageSize);


            ViewBag.SinAsignar = db.Tickets.Where(d => d.Estados.Nombre == "Nuevo").Count();
            ViewBag.EnProgreso = db.Tickets.Where(d => d.IdEstado == 3).Count();
            ViewBag.Resueltos = db.Tickets.Where(d => d.IdEstado == 4).Count();
            return View(data);

        }

        public ActionResult GestionTickets()
        {
            return View();
        }

        public ActionResult ListaGestionTickets()
        {
            var usuario = SessionPersister.Id;

            var data = db.Tickets.Where(t => t.IdAsignado == usuario && t.Estados.EsFinal == true).Include(d => d.Estados).Include(t => t.TipoCaso).Include(e => e.Estados).Include(a => a.Area).Include(u => u.User).Include(c => c.User.Campana).Include(a => a.Users).ToList();

            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult MisTickets()
        {
            ViewBag.PrioridadAlta = Constants.PrioridadAlta;
            ViewBag.PrioridadMedia = Constants.PrioridadMedia;
            ViewBag.PrioridadBaja = Constants.PrioridadBaja;
            return View();
        }

        public ActionResult ListarTicketsAsesor()
        {
            var usuario = SessionPersister.Id;
            List<Tickets> data = null;

            data = db.Tickets.Where(t => t.IdUsuario == usuario).Include(d => d.Estados).Include(t => t.TipoCaso).Include(e => e.Estados).Include(a => a.Area).Include(u => u.User).Include(c => c.User.Campana).Include(a => a.Users).ToList();


            //var serializer = new System.Web.Script.Serialization.JavaScriptSerializer();
            //serializer.MaxJsonLength = 500000000;

            var json = Json(new { data = data }, JsonRequestBehavior.AllowGet);
            json.MaxJsonLength = 500000000;

            return json;
        }


        // GET: Tickets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tickets tickets = db.Tickets.Find(id);
            if (tickets == null)
            {
                return HttpNotFound();
            }
            return View(tickets);
        }

        // GET: Tickets/Create
        public ActionResult Create(string id)
        {

            ViewBag.Documento = db.Usuario.Where(u => u.Documento == id).Select(s => s.Documento).FirstOrDefault();
            ViewBag.IdUsuario = db.Usuario.Where(u => u.Documento == id && u.Estado == true).Select(s => s.Id).FirstOrDefault();
            ViewBag.IdArea = new SelectList(db.Areas, "Id", "Nombre");

            return View();
        }


        public JsonResult AsignarTicketUsuario(usuarioSeleccion usuarioSeleccion)
        {
            var usuarioActual = SessionPersister.Id;

            foreach (var seleccionado in usuarioSeleccion.Id)
            {

                var actual = db.Tickets.Where(t => t.Id == seleccionado).FirstOrDefault();

                db.Entry(actual).State = EntityState.Modified;
                db.Entry(actual).Entity.IdAsignado = Convert.ToInt32(usuarioSeleccion.IdAsignado);
                db.Entry(actual).Entity.IdAsignadoPor = usuarioActual;
                db.Entry(actual).Entity.ActualizadoPor = SessionPersister.Id;
                db.Entry(actual).Entity.Modalidad = actual.Modalidad;
                db.Entry(actual).Entity.IdEstado = 2;
                //fecha desde la creación hasta asignado
                db.Entry(actual).Entity.UpdatedAt = DateTime.Now;
                db.SaveChanges();

                HistorialTickets(actual);

            }
            return Json(new { type = "OK", message = "El ticket se asigno correctamente al usuario " }, JsonRequestBehavior.DenyGet);
        }


        public JsonResult CargarEvidenciaCaso(string documento, string area, string idTipoCaso)
        {

            try
            {

                if (Request.Files.Count > 0)
                {
                    var test = Request.Files[0];

                    string nombreArchivo = "Gestion_" + documento + "_TIPO_";

                    nombreArchivo = nombreArchivo + idTipoCaso + "_AREA_" + area;
                    nombreArchivo = nombreArchivo + ".jpg";

                    string nombre_archivo = @"\\172.16.5.132\Repositorio_Aplicaciones\imagenes_helpDesk\" + nombreArchivo;

                    test.SaveAs(nombre_archivo);

                }

            }
            catch (Exception ex)
            {
                return Json(new { type = "ERROR", message = "La evidencia no se pudo cargar " }, JsonRequestBehavior.DenyGet);
            }

            return Json(new { type = "OK", message = "La evidencia se cargo correctamente" }, JsonRequestBehavior.DenyGet);
        }


        public JsonResult ObtenerTipoCaso(int? IdArea)
        {

            var tiposCaso = db.TipoCasos.Where(t => t.IdArea == IdArea && t.Estado == true).OrderBy(c => c.Nombre).ToList();

            return Json(tiposCaso, JsonRequestBehavior.AllowGet);

TicketsUNO27/Views/Tickets/ListaEstadoTickets.cshtml
@model PagedList.IPagedList<AppRecordatorio.Models.TicketsCasos.Tickets>
@using PagedList.Mvc


@{
    /**/

    ViewBag.Title = "ListaEstadoTickets";
}

@{
    ViewBag._Active = "ListaEstadoTickets";
    ViewBag._Panel = "Home";
}


<style>
    .CellWithComment {
        max-width: 200px;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }
</style>

<br />
<br />
<div class=" segment">
    <h1 class="ui header">
        <img src="~/Content/images/helpdesk.png">
        <div class="content">
            Módulo  Estado  de Tickets
            <div class="sub header">
                <div class="ui breadcrumb">
                    <a class="section" href="@Url.Action("HomeAdmin","Home")">Inicio</a>
                    <div class="divider"> / </div>
                    <div class="active section" style="text-transform:lowercase">Lista  de Tickets</div>
                </div>
            </div>
        </div>
    </h1>
    <div class="ui hidden divider"></div>
</div>
<h4 class="ui horizontal divider header">
    Estado Tickets

</h4>


<div class="ui  form segment">
    @using (Html.BeginForm("ListaEstadoTickets", "Tickets", FormMethod.Get))
    {


    <div class="fields">
        <div class="field">
            <label># Ticket</label>
            <input type="text" name="ticket" placeholder="# ticket">
        </div>
        <div class="field">
            <label>Estado Ticket</label>
            <select name="estado" id="estado">
                <option value="">Seleccione</option>
                <option value="1">Sin asignar</option>
                <option value="3">En progreso</option>
                <option value="4">Resueltos</option>
            </select>
        </div>
        <div class="field">
            <label>Buscar</label>
            <input type="submit" name="submit" value="Buscar" class="ui positive button" />
        </div>

    </div>

    <div class="fields">
        <div class="field">
            <label style="color:red">Tickets sin asignar</label> @ViewBag.SinAsignar
        </div>
        <div class="field">
            <label style="color:orange">Tickets en progreso</label> @ViewBag.EnProgreso
        </div>
        <div class="field">
            <label style="color:forestgreen">Tickets resueltos</label> @ViewBag.Resueltos
        </div>
    </div>
    }
</div>

<div class="ui grid">
    <div class="sixteen wide column">
        <div class="ui segments">
            <div class="ui teal segment">
                <table id="tabla" class="ui celled small hover striped table">

                    <thead>
                        <tr>
                            <th># Ticket</th>
                            <th>Incidencia</th>
                            <th>Respuesta</th>
                            <th>Tipo Caso</th>
                            <th>Ticket Asignado a</th>
                            <th>Estado Ticket</th>
                            <th>Usuario Documento</th>
                            <th>Celular</th>
                            <th>Campaña</th>
                            <th>Fecha Creación</th>
                            <th>Fecha Finalización</th>
                            <th>Detalle</th>
                        </tr>
                    </thead>

                    @if (Model != null)
                    {
                        <tbody>

                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>
                                <td class="CellWithComment">
                                    @Html.DisplayFor(modelItem => item.Incidente)
                                </td>
                                <td class="CellWithComment">
                                    @Html.DisplayFor(modelItem => item.Respuesta)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TipoCaso.Nombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Users.Nombres)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Estados.Nombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.User.Documento)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.User.Celular)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.User.Campana.Nombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CreatedAt)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.FechaFinalizacion)
                                </td>
                                <td>
                                    <a class="ui positive button" href="@Url.Action("ResumentTicket","DetalleEstadoTicket",new { id = item.Id } )">Detalle</a>
                                    @*@Html.ActionLink("DetalleEstadoTicket", "ResumentTicket", new { id = item.Id }, new { @class = "ui green button" })*@
                                </td>
                            </tr>
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <th colspan="9">

                                    @Html.PagedListPager(Model, page => Url.Action("ListaEstadoTickets", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }), PagedListRenderOptionsSemantic.semantic)
                                </th>
                            </tr>

                        </tfoot>

                    }


                </table>
            </div>
        </div>
    </div>
</div>





@*<div class="ui grid">
        <div class="sixteen wide column">
            <div class="ui segments">
                <div class="ui teal segment">
                    <form id="frm-example">

                        <table id="tblEstadoTickets" class="ui celled small hover striped table" style="width:100%">
                            <thead>
                                <tr>
                                    <th># Ticket</th>
                                    <th>Incidencia</th>
                                    <th>Respuesta</th>
                                    <th>Ticket Asignado a</th>
                                    <th>Estado Ticket</th>
                                    <th>Usuario Documento</th>
                                    <th>Usuario Nombres Apellidos</th>
                                    <th>Celular</th>
                                    <th>ANY DESK</th>
                                    <th>Campaña</th>
                                    <th>Area</th>
                                    <th>Tipo Caso</th>
                                    <th>Fecha Creación</th>
                                    <th>Fecha Finalización</th>
                                    <th>Detalle</th>
                                </tr>
                            </thead>
                        </table>

                        <hr>

                        @if (SessionPersister.HasRol("Lider Soporte") || SessionPersister.HasRol("Soporte"))
                        {

                            <div class="field">
                                <a class="ui button" href="@Url.Action("HomeAdmin","Home")">Regresar</a>
                            </div>

                            <br />

                        }




                    </form>
                </div>

            </div>
        </div>

    </div>*@
@section Scripts {
    @*<script src="~/Scripts/datatables.net/js/jquery.dataTables.min.js"></script>
        <link href="~/Content/Datatables/datatables.semantic.min.css" rel="stylesheet" />
        <script src="~/Scripts/datatables.net/js/datatables.semantic.min.js"></script>

        <script src="~/Scripts/app/TicketsGeneral.js"></script>*@


}


@*<div class="ui grid">
        <div class="one wide column"></div>
        <div class="sixteen wide column">
            <div class="ui segments">
                <div class="ui teal segment">
                    <table id="tabla" class="ui celled small hover striped table">
                        <thead>
                            <tr>
                                <th>
                                    # Ticket
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Area.Nombre)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Estados.Nombre)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.TipoCaso.Nombre)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.User.Documento)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Incidente)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Respuesta)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.FechaFinalizacion)
                                </th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Area.Nombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Estados.Nombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TipoCaso.Nombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.User.Documento)
                                </td>

                                <td>
                                    @Html.DisplayFor(modelItem => item.Incidente)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Respuesta)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.FechaFinalizacion)
                                </td>

                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>*@

TicketsUNO27/Views/Tickets/MisTickets.cshtml
@using Core.Models.Security
@model IEnumerable<AppRecordatorio.Models.TicketsCasos.Tickets>

@{
    ViewBag.Title = "MisTickets";
}

@{
    ViewBag._Active = "MisTickets";
    ViewBag._Panel = "Home";
}




<br />
<br />
<div class=" segment">
    <h1 class="ui header">
        <img src="~/Content/images/helpdesk.png">
        <div class="content">
            Módulo  de Lista  de Tickets
            <div class="sub header">
                <div class="ui breadcrumb">
                    <a class="section" href="@Url.Action("HomeAdmin","Home")">Inicio</a>
                    <div class="divider"> / </div>
                    <div class="active section" style="text-transform:lowercase">Lista  de Tickets</div>
                </div>
            </div>
        </div>
    </h1>
    <div class="ui hidden divider"></div>
    <form action="" method="get">
        <a href="@Url.Action("Create", "Tickets", new { id = @SessionPersister.UserName })" , class="ui positive button">
            Crear Nuevo Ticket
        </a>
    </form>
</div>


<div class="ui grid" style="margin-top:10px">

    <div class="eight wide column">
        <div class="ui  form segment">
            <h4>Prioridad Tickets</h4>
            <div class="three fields">
                <div class="field">
                    <label style="background-color:red; color:white">ALTA</label>
                    <div class="ui mini icon input">
                        @ViewBag.PrioridadAlta
                    </div>
                </div>

                <div class="field">
                    <label style="background-color:orangered; color:white">MEDIA</label>
                    <div class="ui mini icon input">
                        @ViewBag.PrioridadMedia
                    </div>
                </div>

                <div class="field">
                    <label style="background-color:orange; color:white">BAJA</label>
                    <div class="ui mini icon input">

                        @ViewBag.PrioridadBaja
                    </div>
                </div>
            </div>



        </div>
    </div>



</div>

<h4 class="ui horizontal divider header">
   
        <i class="tasks icon"></i>
        LISTA DE Tickets


</h4>

<div class="ui grid">
    <div class="sixteen wide column">
        <div class="ui segments">
            <div class="ui teal segment">
                <form id="frm-example">

                    <table id="tblTicketsAsesor" class="ui celled small hover striped table" style="width:100%">
                        <thead>
                            <tr>
                                <th># Ticket</th>
                                <th>Ticket Asignado a</th>
                                <th>Estado Ticket</th>
                                <th>Documento</th>
                                <th>Nombres Apellidos</th>
                                <th>Celular</th>
                                <th>Campaña</th>
                                <th>Area</th>
                                <th>Tipo Caso</th>
                                <th style="background-color:lawngreen">Prioridad</th>
                                <th>Fecha Creación</th>
                                <th>Fecha Finalización</th>
                                <th>Detalle</th>
                            </tr>
                        </thead>
                    </table>

                    <hr>

                    <br />




                </form>
            </div>

        </div>
    </div>

</div>
@section Scripts {
    <script src="~/Scripts/datatables.net/js/jquery.dataTables.min.js"></script>
    <link href="~/Content/Datatables/datatables.semantic.min.css" rel="stylesheet" />
    <script src="~/Scripts/datatables.net/js/datatables.semantic.min.js"></script>
    <script src="~/Scripts/app/TicketsAsesor.js"></script>
}