TicketsUNO27/Controllers/AccountsController.cs
using AppRecordatorio.Models;
using Core.Models.Security;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;


namespace TicketsUNO27.Controllers
{
    public class AccountsController : Controller
    {

        private Contexto db = new Contexto();

        // GET: Accounts
        public ActionResult Index()
        {

            if (SessionPersister.Id != null)
                return RedirectToAction("HomeAdmin", "Home", null);

            return View();
        }

        public ActionResult ResetPassword(string userName, string message)
        {
            if (!string.IsNullOrEmpty(message))
            {
                ViewBag.Error = message;
            }

            ViewBag.UserName = userName;
            return View();
        }


        [HttpPost]
        public ActionResult Login(AccountsViewModel avm)
        {

            AccountsModel am = new AccountsModel();
            Accounts ResultUser = am.Login(avm.Accounts.UserName, avm.Accounts.Password);
            var usuario = avm.Accounts.UserName;
            var password = avm.Accounts.Password;          

            if (string.IsNullOrEmpty(usuario) || string.IsNullOrEmpty(password) || ResultUser == null)
            {
                ViewBag.Error = "Usuario o contraseña incorrectos";
                return View("index");
            }

            // Validamos que la contraseña no sea igual a la del password.
            if (!ValidateUserAndPassword(usuario, password)) return RedirectToAction("ResetPassword", new { userName = avm.Accounts.UserName, message = "El usuario y la contraseña, no pueden se iguales... Debe cambiar la contraseña" });

            


            // get user data for the session.
            SessionPersister.UserName = avm.Accounts.UserName;
            SessionPersister.Id = ResultUser.Id;

            return RedirectToAction("index");

        }

        [HttpPost]
        public ActionResult EditPassword(AccountsViewModel avm)
        {
            var validate = ValidateEditPassWord(avm);

            // Validaciones para la edición de la contraseña.
            if (!validate.Item1) return RedirectToAction("ResetPassword", new { userName = avm.Accounts.UserName, message = validate.Item2 });      

            var user = db.Usuario.Where(x => x.Documento.Trim() == avm.Accounts.UserName).FirstOrDefault();

            // Validamos que el usuario a editar exista.
            if (user == null)
            {
                ViewBag.Error = "El Usuario no existe, consulte con el administrador.";
                return RedirectToAction("index");
            }

            user.Clave = avm.Accounts.Password;
            db.Entry(user).State = EntityState.Modified;
            db.SaveChanges();


            // get user data for the session.
            SessionPersister.UserName = avm.Accounts.UserName;
            SessionPersister.Id = user.Id;

            return RedirectToAction("index");

        }

        private (bool, string) ValidateEditPassWord(AccountsViewModel avm)
        {
            // Validamos que los campos de contraseña no vengan vacíos.
            if (string.IsNullOrEmpty(avm.Accounts.Password) || string.IsNullOrEmpty(avm.Accounts.ConfirmPassword)) return (false, "Las contraseñas no pueden estar vacías...");


            // Validamos que la contraseña no sea igual a la del password.
            if (!ValidateUserAndPassword(avm.Accounts.UserName, avm.Accounts.Password)) return (false, "El usuario y la contraseña, no pueden ser iguales...");
        

            // Validamos que las contraseñas coincidan.
            if (!avm.Accounts.Password.Equals(avm.Accounts.ConfirmPassword)) return (false, "Las contraseñas no coinciden...");
          

            return (true, string.Empty);
        }

        private bool ValidateUserAndPassword(string usuario, string password)
        {
            if (usuario.Equals(password)) return false;

            return true;

        }

        public ActionResult Logout()
        {
            SessionPersister.UserName = string.Empty;
            SessionPersister.Id = null;
            return View("index");
        }


        public ActionResult AccessDenied()
        {
            return View();
        }
    }
}

TicketsUNO27/Controllers/CampanasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppRecordatorio.Models;
using AppRecordatorio.Models.Campanas;
using Core.Models.Security;

namespace TicketsUNO27.Controllers
{
    [CustomAuthorize(Roles = "Administrador")]
    public class CampanasController : Controller
    {
        private Contexto db = new Contexto();

        // GET: Campanas
        public ActionResult Index()
        {
            return View(db.Campanas.ToList());
        }

        // GET: Campanas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Campana campana = db.Campanas.Find(id);
            if (campana == null)
            {
                return HttpNotFound();
            }
            return View(campana);
        }

        // GET: Campanas/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: Campanas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nombre,Estado,CreatedAt,UpdatedAt,DeletedAt,CreatedBy,UpdatedBy")] Campana campana)
        {
            if (ModelState.IsValid)
            {
                db.Campanas.Add(campana);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(campana);
        }

        // GET: Campanas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Campana campana = db.Campanas.Find(id);
            if (campana == null)
            {
                return HttpNotFound();
            }
            return View(campana);
        }

        // POST: Campanas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nombre,Estado,CreatedAt,UpdatedAt,DeletedAt,CreatedBy,UpdatedBy")] Campana campana)
        {
            if (ModelState.IsValid)
            {
                db.Entry(campana).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(campana);
        }

        // GET: Campanas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Campana campana = db.Campanas.Find(id);
            if (campana == null)
            {
                return HttpNotFound();
            }
            return View(campana);
        }

        // POST: Campanas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Campana campana = db.Campanas.Find(id);
            db.Campanas.Remove(campana);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TicketsUNO27/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppRecordatorio.Models;
using Core.Models.Security;
using Core.Models.User;


namespace TicketsUNO27.Controllers
{
    [CustomAuthorize(Roles = "Administrador")]
    public class UsersController : Controller
    {
        private Contexto db = new Contexto();

        /*------------------------------------------------------*
        * ADMINISTRACION DE USUARIOS
        *------------------------------------------------------*/

        // GET: Users
        public ActionResult Index()
        {
            return View(db.Usuario.Where(c => c.Estado == true).ToList());
        }

        // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Usuario.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            ViewBag.CampanaId = new SelectList(db.Campanas, "Id", "Nombre");

            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Documento,Nombres,Apellidos,Correo,Estado,Clave,Login,TelefonoFijo,Ceular,CodigoAcceso,CampanaId,UpdatedAt,DeletedAt")] User user)
        {
            ViewBag.CampanaId = new SelectList(db.Campanas, "Id", "Nombre");

            if (ModelState.IsValid)
            {
                //user.Id = Guid.NewGuid();
                db.Entry(user).Entity.Estado = true;
                db.Usuario.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Usuario.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            ViewBag.CampanaId = new SelectList(db.Campanas, "Id", "Nombre", user.CampanaId);
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id, Documento,Nombres,Apellidos,Correo,Estado,Clave,Login,TelefonoFijo,Celular,CodigoAcceso,CampanaId,UpdatedAt,DeletedAt")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CampanaId = new SelectList(db.Campanas.Where(c => c.Id == user.CampanaId), "Id", "Nombre", user.CampanaId);
            return View(user);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Usuario.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Usuario.Find(id);
            db.Usuario.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        /*------------------------------------------------------*
        * ADMINISTRACION DE ROLES
        *------------------------------------------------------*/
        
        public ActionResult Roles(int Id)
        {
            User Usuario = db.Usuario.Find(Id);
            if (Id == null || Usuario == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ViewBag.Name = Usuario.Nombres;
            ViewBag.Id = Id;
            ViewBag.UsersRol = db.UsuariosRoles.Include(u => u.Rol).Include(u => u.User).Where(p => p.UserId == Id);
            ViewBag.RolId = new SelectList(db.Roles, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Roles([Bind(Include = "Id,RolId,UserId")] UserRol userRol, string Name)
        {
            if (ModelState.IsValid)
            {
                var Exist = db.UsuariosRoles
                    .Where(
                    c => c.UserId == userRol.UserId&&
                    c.RolId == userRol.RolId
                ).FirstOrDefault();

                if (Exist != null)
                {
                    ModelState.AddModelError("RolId", "este permiso ya fue asignado");
                }
                else
                {
                    //userRol.Id = Guid.NewGuid();
                    db.UsuariosRoles.Add(userRol);
                    db.SaveChanges();
                    return RedirectToAction("Roles", new { Id = userRol.UserId});
                }


            }
            var Id = userRol.UserId;
            ViewBag.Name = Name;
            ViewBag.Id = Id;
            ViewBag.UsersRol = db.UsuariosRoles.Include(u => u.Rol).Include(u => u.User).Where(p => p.UserId == Id);
            ViewBag.RolId = new SelectList(db.Roles, "Id", "Name");
            return View("Roles");
        }

        // POST: UserOfPointOfCares/Delete/5
        [HttpPost, ActionName("DeleteRol")]
        [ValidateAntiForgeryToken]
        public ActionResult RolesDeleteConfirmed(int id)
        {
            UserRol UsusarioRol = db.UsuariosRoles.Find(id);
            var UserId = UsusarioRol.UserId;
            db.UsuariosRoles.Remove(UsusarioRol);
            db.SaveChanges();
            return RedirectToAction("Roles", new { Id = UserId });
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TicketsUNO27/Views/Shared/_Layout.cshtml
@using Core.Models.Security

@{
    Int32 unixTimestamp = 90;
}



<!DOCTYPE html>
<html>
<head>
    <!-- Standard Meta -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    @Styles.Render("~/Content/css")
    <!-- Site Properties -->
    <title>Help desk uno27 </title>
    @*<link rel="stylesheet" type="text/css" href="~/Content/semantic/components/reset.css">*@
    @*<link rel="stylesheet" type="text/css" href="~/Content/semantic/components/site.css">*@
    <link rel="stylesheet" type="text/css" href="~/Content/semantic/components/tab.css">
    <link rel="stylesheet" type="text/css" href="~/Content/Site.css">
    <link href="~/Content/semantic/semantic.min.css" rel="stylesheet" />
    @*<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />*@



    <style type="text/css">

        .hidden.menu {
            display: none;
        }

        .masthead.segment {
            min-height: 700px;
            padding: 1em 0em;
        }

        .masthead .logo.item img {
            margin-right: 1em;
        }

        .masthead .ui.menu .ui.button {
            margin-left: 0.5em;
        }

        .masthead h1.ui.header {
            margin-top: 3em;
            margin-bottom: 0em;
            font-size: 4em;
            font-weight: normal;
        }

        .masthead h2 {
            font-size: 1.7em;
            font-weight: normal;
        }

        .ui.vertical.stripe {
            padding: 8em 0em;
        }

            .ui.vertical.stripe h3 {
                font-size: 2em;
            }

            .ui.vertical.stripe .button + h3,
            .ui.vertical.stripe p + h3 {
                margin-top: 3em;
            }

            .ui.vertical.stripe .floated.image {
                clear: both;
            }

            .ui.vertical.stripe p {
                font-size: 1.33em;
            }

            .ui.vertical.stripe .horizontal.divider {
                margin: 3em 0em;
            }

        .quote.stripe.segment {
            padding: 0em;
        }

            .quote.stripe.segment .grid .column {
                padding-top: 5em;
                padding-bottom: 5em;
            }

        .footer.segment {
            padding: 5em 0em;
        }

        .secondary.pointing.menu .toc.item {
            display: none;
        }

        #contenidoApp {
            padding-left: 20px;
            padding-right: 20px;
            padding-top: 20px;
        }

        @@media only screen and (max-width: 700px) {
            #contenidoApp {
                margin-left: 10px;
            }

            .ui.fixed.menu {
                display: none !important;
            }

            .secondary.pointing.menu .item,
            .secondary.pointing.menu .menu {
                display: none;
            }

            .secondary.pointing.menu .toc.item {
                display: block;
            }

            .masthead.segment {
                min-height: 350px;
            }

            .masthead h1.ui.header {
                font-size: 2em;
                margin-top: 1.5em;
            }

            .masthead h2 {
                margin-top: 0.5em;
                font-size: 1.5em;
            }
        }
    </style>


</head>

<body>

    <!-- Following Menu -->
    <!-- Sidebar Menu -->
    <!-- Page Contents -->

    <div class="ui modal fullscreen" id="loadmodalData">
        <i class="close icon"></i>
        <div class="content" id="data">
        </div>
    </div>

    <div class="ui fixed inverted black menu">
        <div class="item">
            <img alt="logoBlanco" class="" src="~/Content/images/Logo Blanco.png">
        </div>
        @if (SessionPersister.Id != null)
        {
            @Html.Partial("_Menu");
        }
    </div>
    <div class="" id="contenidoApp">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/js")

    <script>
            const BaseUrl =  @Html.Raw(HttpUtility.JavaScriptStringEncode(Url.Content("~/"), true));
            let isAgente = false;
    </script>
    <script src="~/Content/semantic/semantic.min.js"></script>
    @*<script src="~/Scripts/app/General.js?v=@unixTimestamp"></script>*@


    <!--tiny mce-->

    @RenderSection("scripts", required: false)

    <script>
        $(document)
            .ready(function () {
                // fix menu when passed
                $('.masthead')
                    .visibility({
                        once: false,
                        onBottomPassed: function () {
                            $('.fixed.menu').transition('fade in');
                        },
                        onBottomPassedReverse: function () {
                            $('.fixed.menu').transition('fade out');
                        }
                    });
                $(".ui.sidebar").sidebar()
                $('.ui.dropdown').dropdown();
                $('.tabular.menu .item').tab();


            });
    </script>

</body>

</html>

TicketsUNO27/Views/Shared/_LayoutLogin.cshtml
@using Core.Models.Security

@{
    Int32 unixTimestamp = 21;
}



<!DOCTYPE html>
<html>
<head>
    <!-- Standard Meta -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <!-- Site Properties -->
    <title>Service desk - Uno27</title>
    <link href="~/Content/semantic/semantic.min.css" rel="stylesheet" />
    <style type="text/css">

    .hidden.menu {
      display: none;
    }

    .masthead.segment {
      min-height: 700px;
      padding: 1em 0em;
    }
    .masthead .logo.item img {
      margin-right: 1em;
    }
    .masthead .ui.menu .ui.button {
      margin-left: 0.5em;
    }
    .masthead h1.ui.header {
      margin-top: 3em;
      margin-bottom: 0em;
      font-size: 4em;
      font-weight: normal;
    }
    .masthead h2 {
      font-size: 1.7em;
      font-weight: normal;
    }

    .ui.vertical.stripe {
      padding: 8em 0em;
    }
    .ui.vertical.stripe h3 {
      font-size: 2em;
    }
    .ui.vertical.stripe .button + h3,
    .ui.vertical.stripe p + h3 {
      margin-top: 3em;
    }
    .ui.vertical.stripe .floated.image {
      clear: both;
    }
    .ui.vertical.stripe p {
      font-size: 1.33em;
    }
    .ui.vertical.stripe .horizontal.divider {
      margin: 3em 0em;
    }

    .quote.stripe.segment {
      padding: 0em;
    }
    .quote.stripe.segment .grid .column {
      padding-top: 5em;
      padding-bottom: 5em;
    }

    .footer.segment {
      padding: 5em 0em;
    }

    .secondary.pointing.menu .toc.item {
      display: none;
    }

    @@media only screen and (max-width: 700px) {
      .ui.fixed.menu {
        display: none !important;
      }
      .secondary.pointing.menu .item,
      .secondary.pointing.menu .menu {
        display: none;
      }
      .secondary.pointing.menu .toc.item {
        display: block;
      }
      .masthead.segment {
        min-height: 350px;
      }
      .masthead h1.ui.header {
        font-size: 2em;
        margin-top: 1.5em;
      }
      .masthead h2 {
        margin-top: 0.5em;
        font-size: 1.5em;
      }
    }


    </style>

    
</head>
<body class="hold-transition skin-black-light sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">


        <!-- =============================================== -->
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper bodyback">
            <section class="content">
                @RenderBody()
            </section>
        </div>
        <footer class="main-footer">
            @Html.Partial("_Footer")
        </footer>

    <!-- ./wrapper -->
    <!-- jQuery 3 -->

    @Scripts.Render("~/bundles/js")

    <script>
        const BaseUrl =  @Html.Raw(HttpUtility.JavaScriptStringEncode(Url.Content("~/"), true));
        let isAgente = false;
    </script>


    <script src="~/Content/semantic/components/visibility.min.js"></script>
    <script src="~/Content/semantic/components/sidebar.js"></script>
    <script src="~/Content/semantic/components/transition.js"></script>
    <script>
        $(document)
            .ready(function () {

                // fix menu when passed
                $('.masthead')
                    .visibility({
                        once: false,
                        onBottomPassed: function () {
                            $('.fixed.menu').transition('fade in');
                        },
                        onBottomPassedReverse: function () {
                            $('.fixed.menu').transition('fade out');
                        }
                    })
                    ;

                // create sidebar and attach to menu open
                $('.ui.sidebar')
                    .sidebar('attach events', '.toc.item')
                    ;

            })
            ;
    </script>

    @RenderSection("scripts", required: false)
</body>

</html>

TicketsUNO27/Views/Shared/_Menu.cshtml
@using Core.Models.Security
@using tmkhogares.ViewModel
<!-- /.search form -->
<!-- sidebar menu: : style can be found in sidebar.less -->

@if (SessionPersister.HasRol("Administrador"))
{
    <div class="ui dropdown item">
        Usuarios
        <i class="dropdown icon"></i>
        <div class="menu">
            <a href="@Url.Action("Create", "Users")" class="item"><i class="user plus icon"></i> Crear usuario</a>
            <a href="@Url.Action("index", "Users")" class="item"><i class="user plus icon"></i> Lista de usuarios</a>
        </div>
    </div>

}
<!--|==================================================================|-->
<!--|             MENU DE TIPO CASO                              |-->
<!--|==================================================================|-->
@*@if (SessionPersister.HasRol("Administrador"))
    {
        <div class="ui dropdown item">
            Tipos de Caso
            <i class="dropdown icon"></i>
            <div class="menu">
                <a href="@Url.Action("create","tipocasoes")" class="item"><i class="edit icon"></i>Crear tipos de caso</a>
                <a href="@Url.Action("index","tipocasoes")" class="item"><i class="edit icon"></i>Lista tipos de caso</a>
            </div>
        </div>

    }*@


<!--|==================================================================|-->
<!--|             MENU DE CAMPAÑAS                              |-->
<!--|==================================================================|-->


@if (SessionPersister.HasRol("Administrador"))
{
    <div class="ui dropdown item">
        Campaña
        <i class="dropdown icon"></i>
        <div class="menu">
            <a href="@Url.Action("create","Campanas")" class="item"><i class="edit icon"></i>Crear campaña</a>
            <a href="@Url.Action("index","Campanas")" class="item"><i class="edit icon"></i>Lista de campañas</a>
        </div>
    </div>

}

@if (SessionPersister.HasRol("Administrador"))
{
    <div class="ui dropdown item">
        Cargue Masivo Usuarios
        <i class="dropdown icon"></i>
        <div class="menu">
            <a href="@Url.Action("Index","CargueUsuarios")" class="item"><i class="edit icon"></i>Cargue Usuarios</a>
        </div>
    </div>

}

<div class="right menu">

    <a href="@Url.Action("Logout","Accounts")" class="item"><i class="close icon"></i>Cerrar Session</a>

</div>


<style>
    .sidebar-collapse .crosselinglogo {
        display: none;
    }
</style>