TicketsUNO27/Models/Security/Accounts.cs
namespace Core.Models.Security
{
    public class Accounts
	{
		public int? Id { get; set; }
		public string UserName { get; set; }
		public string Password { get; set; }
		public string ConfirmPassword { get; set; }
		public string[] Roles { get; set; }
	}
}

TicketsUNO27/Controllers/AccountsController.cs
using AppRecordatorio.Models;
using Core.Models.Security;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;


namespace TicketsUNO27.Controllers
{
    public class AccountsController : Controller
    {

        private Contexto db = new Contexto();

        // GET: Accounts
        public ActionResult Index()
        {

            if (SessionPersister.Id != null)
                return RedirectToAction("HomeAdmin", "Home", null);

            return View();
        }

        public ActionResult ResetPassword(string userName, string message)
        {
            if (!string.IsNullOrEmpty(message))
            {
                ViewBag.Error = message;
            }

            ViewBag.UserName = userName;
            return View();
        }


        [HttpPost]
        public ActionResult Login(AccountsViewModel avm)
        {

            AccountsModel am = new AccountsModel();
            Accounts ResultUser = am.Login(avm.Accounts.UserName, avm.Accounts.Password);
            var usuario = avm.Accounts.UserName;
            var password = avm.Accounts.Password;          

            if (string.IsNullOrEmpty(usuario) || string.IsNullOrEmpty(password) || ResultUser == null)
            {
                ViewBag.Error = "Usuario o contraseña incorrectos";
                return View("index");
            }

            // Validamos que la contraseña no sea igual a la del password.
            if (!ValidateUserAndPassword(usuario, password)) return RedirectToAction("ResetPassword", new { userName = avm.Accounts.UserName, message = "El usuario y la contraseña, no pueden se iguales... Debe cambiar la contraseña" });

            


            // get user data for the session.
            SessionPersister.UserName = avm.Accounts.UserName;
            SessionPersister.Id = ResultUser.Id;

            return RedirectToAction("index");

        }

        [HttpPost]
        public ActionResult EditPassword(AccountsViewModel avm)
        {
            var validate = ValidateEditPassWord(avm);

            // Validaciones para la edición de la contraseña.
            if (!validate.Item1) return RedirectToAction("ResetPassword", new { userName = avm.Accounts.UserName, message = validate.Item2 });      

            var user = db.Usuario.Where(x => x.Documento.Trim() == avm.Accounts.UserName).FirstOrDefault();

            // Validamos que el usuario a editar exista.
            if (user == null)
            {
                ViewBag.Error = "El Usuario no existe, consulte con el administrador.";
                return RedirectToAction("index");
            }

            user.Clave = avm.Accounts.Password;
            db.Entry(user).State = EntityState.Modified;
            db.SaveChanges();


            // get user data for the session.
            SessionPersister.UserName = avm.Accounts.UserName;
            SessionPersister.Id = user.Id;

            return RedirectToAction("index");

        }

        private (bool, string) ValidateEditPassWord(AccountsViewModel avm)
        {
            // Validamos que los campos de contraseña no vengan vacíos.
            if (string.IsNullOrEmpty(avm.Accounts.Password) || string.IsNullOrEmpty(avm.Accounts.ConfirmPassword)) return (false, "Las contraseñas no pueden estar vacías...");


            // Validamos que la contraseña no sea igual a la del password.
            if (!ValidateUserAndPassword(avm.Accounts.UserName, avm.Accounts.Password)) return (false, "El usuario y la contraseña, no pueden ser iguales...");
        

            // Validamos que las contraseñas coincidan.
            if (!avm.Accounts.Password.Equals(avm.Accounts.ConfirmPassword)) return (false, "Las contraseñas no coinciden...");
          

            return (true, string.Empty);
        }

        private bool ValidateUserAndPassword(string usuario, string password)
        {
            if (usuario.Equals(password)) return false;

            return true;

        }

        public ActionResult Logout()
        {
            SessionPersister.UserName = string.Empty;
            SessionPersister.Id = null;
            return View("index");
        }


        public ActionResult AccessDenied()
        {
            return View();
        }
    }
}

TicketsUNO27/Controllers/FormUsuarioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppRecordatorio.Models;
using Core.Models.User;

namespace TicketsUNO27.Controllers
{
    public class FormUsuarioController : Controller
    {
        private Contexto db = new Contexto();

        // GET: FormUsuario
        public ActionResult Index()
        {
            var usuario = db.Usuario.Include(u => u.Campana);
            return View(usuario.ToList());
        }

        // GET: FormUsuario/Create
        public ActionResult Create()
        {
            ViewBag.CampanaId = new SelectList(db.Campanas, "Id", "Nombre");
            return View();
        }

        // POST: FormUsuario/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        public ActionResult Create([Bind(Include = "Id,Documento,Nombres,Apellidos,Correo,Estado,Clave,Login,TelefonoFijo,Celular,CodigoAcceso,CampanaId,CreatedAt,UpdatedAt,DeletedAt,CreatedBy,UpdatedBy")] User user)
        {
            try
            {

                //VALIDAR SI USUARIO YA EXISTE
                var usuario = db.Usuario.Where(d => d.Documento == user.Documento).ToList().Count();

                if (usuario == 1)
                {
                    return Json(new { type = "ERROR", message = "El usuario ya se encuentra registrado consulte con el administrador." }, JsonRequestBehavior.DenyGet);
                }
                else
                {
                    if (ModelState.IsValid)
                    {

                        db.Entry(user).Entity.Estado = true;

                        db.Usuario.Add(user);

                        db.SaveChanges();

                        //id insertado
                        int id = user.Id;

                        //crear rol usuario asesor
                        UserRol rol = new UserRol();

                        rol.RolId = 4;
                        rol.UserId = id;
                        db.UsuariosRoles.Add(rol);
                        db.SaveChanges();
                    }
                }


            }
            catch (Exception ex)
            {
                return Json(new { type = "ERROR", message = "Error al registrar usuario consulte con el administrador." }, JsonRequestBehavior.DenyGet);
            }

            ViewBag.CampanaId = new SelectList(db.Campanas, "Id", "Nombre", user.CampanaId);
            return Json(new { type = "OK", message = "Usuario Registrado Correctamente." }, JsonRequestBehavior.DenyGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TicketsUNO27/Views/Accounts/AccessDenied.cshtml
@{
    ViewBag.Title = "Index";
}



<div class="container py-5">
    <div class="row">
        <div class="col-md-2 text-center">
            <p><i class="fa fa-exclamation fa-5x"></i><br />Status Code: 403</p>
        </div>
        <div class="col-md-10">
            <h3>OPPSSS!!!! Lo siento...</h3>
            <p>Lo siento,No tienes acceso a esta pagina  por razones de seguridad y de datos sensibles.<br />por favor regresa a la pagina anterior para que sigas Revisando.</p>
            <a class="btn btn-danger" href="javascript:history.back()">Regresar</a>
        </div>
    </div>
</div>

<div id="footer" class="text-center">
    &copy;Uno27 2018, Todos los derechos reservados.
</div>

TicketsUNO27/Views/Accounts/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/shared/_LayoutLogin.cshtml";

}
@model  Core.Models.Security.AccountsViewModel


<style>
    .masthead.segment {
        min-height: 350px;
        padding: 1em 0em;
    }

    .masthead {
        background: url('/Content/images/Service_Desk.png') !important;
        background-repeat: no-repeat;
        background-position: center !important;
    }
</style>


<div class="ui large top fixed hidden menu">
    <div class="ui container">
        <a class="active item">Gestionar</a>
        <div class="right menu">
            <div class="item">
                <a class="ui button">Ingresar</a>
            </div>
        </div>
    </div>
</div>


<!-- menu lateral  -->
<div class="ui inverted vertical masthead center aligned segment">
    @*<div class="ui container">
            <div class="ui large secondary inverted pointing menu">
                <a class="toc item">
                    <i class="sidebar icon"></i>
                </a>
                <a class="active item">Gestionar</a>
                <div class="right item">
                    <a href="#login" class="ui inverted button">Ingresar</a>
                </div>
            </div>
        </div>
        <div class="ui text container">
            <h1 class="ui inverted header">
                27 SERVICE DESK
            </h1>
            <h2>Gestion de tickets.</h2>
            <a href="#login" class="ui huge primary button">Ingresar <i class="right arrow icon"></i></a>
        </div>*@

</div>

<div class="ui vertical stripe segment" id="login">
    <div class="ui middle aligned stackable grid container">
        <div class="row">
            <div class="eight wide column">
                <h3 class="ui header">Ingresa al sistema</h3>
                <p>Si tienes problema para ingresar por favor contacta al administrador</p>


                @using (Html.BeginForm("Login", "Accounts", FormMethod.Post, new { @class = "ui large form", autofocus = "" }))
                {


                    <div class="ui stacked segment">
                        <div class="field">
                            <div class="ui left icon input">
                                <i class="user icon"></i>
                                @Html.EditorFor(model => model.Accounts.UserName, new { htmlAttributes = new { @class = "", autofocus = "", @placeholder = "Ingrese su documento" } })
                            </div>
                        </div>
                        <div class="field">
                            <div class="ui left icon input">
                                <i class="lock icon"></i>
                                @Html.EditorFor(model => model.Accounts.Password, new { htmlAttributes = new { @class = "", @placeholder = "Ingrese la contraseña", type = "password" } })
                            </div>
                        </div>
                        @*<div class="two fields">*@
                        <div class="field">
                            <input type="submit" name="send" value="Ingresar" class="ui fluid  red submit button" />

                        </div>
                        @*<div class="field">
                                <a class="ui fluid red submit button" href="@Url.Action("Create","FormUsuario")">Registrar</a>

                            </div>*@
                        @*</div>*@

                    </div>

                    if (ViewBag.Error != null)
                    {

                        <div class="ui error visible  message">@ViewBag.Error</div>
                    }




                }




            </div>
            <div class="six wide right floated column">

                <img src="~/Content/images/helpdesk.png" class="ui large green rounded image">
                @*<img src="~/Content/images/Logo Negro.png" class="ui large green rounded image" style="height:190px; width:300px">*@
            </div>
        </div>

    </div>
</div>




<div class="ui inverted vertical footer segment">
    <div class="ui container">
        <div class="ui stackable inverted divided equal height stackable grid">
            @*<div class="three wide column">
                    <h4 class="ui inverted header">About</h4>
                    <div class="ui inverted link list">
                        <a href="#" class="item"></a>
                        <a href="#" class="item"></a>
                        <a href="#" class="item"></a>
                        <a href="#" class="item"></a>
                    </div>
                </div>
                <div class="three wide column">
                    <h4 class="ui inverted header">Services</h4>
                    <div class="ui inverted link list">
                        <a href="#" class="item"></a>
                        <a href="#" class="item"></a>
                        <a href="#" class="item"></a>
                        <a href="#" class="item"></a>
                    </div>
                </div>
                <div class="seven wide column">
                    <h4 class="ui inverted header">Footer Header</h4>
                    <p></p>
                </div>*@
        </div>
    </div>
</div>





@section Scripts{
    <script>
        // create sidebar and attach to menu open
        $('.ui.sidebar')
            .sidebar('attach events', '.toc.item')
            ;

    </script>
}

TicketsUNO27/Views/Accounts/ResetPassword.cshtml
@model  Core.Models.Security.AccountsViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/shared/_LayoutLogin.cshtml";
  

}


<style>
    .masthead.segment {
        min-height: 350px;
        padding: 1em 0em;
    }

    .masthead {
        background: url('/Content/images/Service_Desk.png') !important;
        background-repeat: no-repeat;
        background-position: center !important;
    }
</style>


<div class="ui large top fixed hidden menu">
    <div class="ui container">
        <a class="active item">Gestionar</a>
        <div class="right menu">
            <div class="item">
                <a class="ui button">Ingresar</a>
            </div>
        </div>
    </div>
</div>

<!-- menu lateral  -->
<div class="ui inverted vertical masthead center aligned segment">


</div>


<div class="ui vertical stripe segment" id="login">
    <div class="ui middle aligned stackable grid container">
        <div class="row">
            <div class="eight wide column">
                <h3 class="ui header">Cambio de Contraseña</h3>
                <p>Si tienes problema para ingresar por favor contacta al administrador</p>


                @using (Html.BeginForm("EditPassword", "Accounts", FormMethod.Post, new { @class = "ui large form", autofocus = "" }))
                {

                    @Html.HiddenFor(m => m.Accounts.UserName, new { Value = ViewBag.UserName })
                    <div class="ui stacked segment">
                        <div class="field">
                            <label>Usuario</label>
                            <div class="ui left icon input">
                                <i class="user icon"></i>
                                <input type="text" class="text-box single-line" name="usernaNameHidden" id="usernaNameHidden" value="@ViewBag.UserName" placeholder="Ingrese su documento" disabled />                              
                            </div>
                        </div>
                        <div class="field">
                            <label>Nueva Contraseña</label>
                            <div class="ui left icon input">
                                <i class="lock icon"></i>
                                @Html.EditorFor(model => model.Accounts.Password, new { htmlAttributes = new { @class = "", @placeholder = "Ingrese la contraseña", type = "password" } })
                            </div>
                        </div>
                        <div class="field">
                            <label>Confirmar Contraseña</label>
                            <div class="ui left icon input">
                                <i class="lock icon"></i>
                                @Html.EditorFor(model => model.Accounts.ConfirmPassword, new { htmlAttributes = new { @class = "", @placeholder = "Confirme la contraseña", type = "password" } })
                            </div>
                        </div>

                        <div class="field">
                            <input type="submit" name="send" value="Actualizar" class="ui fluid  red submit button" />

                        </div>

                    </div>

                    if (ViewBag.Error != null)
                    {

                        <div class="ui error visible  message">@ViewBag.Error</div>
                    }



                }



            </div>
            <div class="six wide right floated column">

                <img src="~/Content/images/helpdesk.png" class="ui large green rounded image">

            </div>
        </div>

    </div>
</div>


<div class="ui inverted vertical footer segment">
    <div class="ui container">
        <div class="ui stackable inverted divided equal height stackable grid">
       
        </div>
    </div>
</div>


@section Scripts{
    <script>
        // create sidebar and attach to menu open
        $('.ui.sidebar')
            .sidebar('attach events', '.toc.item')
            ;

    </script>
}